services:
  - type: web
    name: ilmportal-backend
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRE
        value: 30d
      - key: SMTP_USER
        value: info@ilmidunya.com
      - key: SMTP_FROM
        value: info@ilmidunya.com
      - key: ADMIN_EMAIL
        value: info@ilmidunya.com
      - key: RESEND_FROM
        value: "IlmiDunya Pakistan <info@ilmidunya.com>"
      - key: SMTP_PASS
        sync: false
      - key: MONGODB_URI
        sync: false

